config:
  data:
    x: 720
    y: 360
    in_channels: 5
    out_channels: 5

  model:
    z_channels: 4
    embed_dim: 4
    channels: 32
    channel_mult: [1, 2, 4, 4]
    num_res_blocks: 2
    norm_groups: 32
    attention: False
    num_heads: 4

  loss:
    reconstruction_loss: l1
    kl_weight: 0.000001

  training:
    learning_rate: 0.001
    epochs: 10
    batch_size: 1
    lr_scheduler: None